apiVersion: apps/v1
kind: Deployment
metadata:
    name: infer
    labels:
        app: api
spec:
    replicas: 3
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
        spec:
            containers:
                - name: infer
                  image: charllechen/mnist-k8s
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: infer-end
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: my-balance
    protocol: TCP
    port: 5000
    targetPort: 5000